# See https://redoc.ly/docs/cli/configuration/ for more information.
apiDefinitions:
  main: openapi/openapi.yaml
lint:
  extends:
    - recommended
  rules:
    no-unused-components: warning
referenceDocs:
  htmlTemplate: ./docs/index.html
  expandResponses: "200"
  jsonSampleExpandLevel: 1
  theme:
    colors:
      primary:
        main: "#32329f"
